### ISSUE TITLE
where are you?

### ISSUE THREAD

**Issue by SniperM99** [40660367/VideoTeach#3]
where are you? @40660367 
`import pandas as pd`
[me](https://github.com/SniperM99)

**Comment by 40660367** [comment]
Python代码要这么写
```python
import numpy as np

def a():
   pass

```

**Comment by SniperM99** [comment]
#! /bin/bash
这个有什么作用啊? 我发现经常在linux的Python代码中有,但是Windows中很少有

**Comment by 40660367** [comment]
在linux中，第一行的
```
#! /bin/bash
```
起到当这个文件可以bash直接执行时（x权限 ），它去找指定的解释器的作用

**Comment by SniperM99** [comment]
[关于Python安装的问题](https://github.com/40660367/VideoTeach/projects/1#card-19020557)请解答
