### ISSUE TITLE
对于Python中 的#! /bin/bash还是不太明白

### ISSUE THREAD

**Issue by SniperM99** [40660367/VideoTeach#6]
#! /bin/bash
这个有什么作用啊? 我发现经常在linux的Python代码中有,但是Windows中很少有

_Originally posted by @SniperM99 in https://github.com/40660367/VideoTeach/issues/3#issuecomment-474165603_

**Comment by SniperM99** [comment]
以上操作是: 问题中的问题. 可以追根到 #3 (comment)

**Comment by 40660367** [comment]
不明白，多做做，就明白了。

**Comment by 40660367** [comment]
相当于对#3的引用

**Comment by SniperM99** [comment]
> 相当于对#3的引用

是的,,还能对记录中的某个点,进行专项回复

**Comment by SniperM99** [comment]
@40660367 太方便
